zmon-controller:
  image_version: "cd450"
  env_vars:
    "SERVER_PORT": 443
    "MANAGEMENT_PORT": 8079
    "MANAGEMENT_SECURITY_ENABLED": false
    "MEM_JAVA_PERCENT": 25
    "POSTGRES_URL": jdbc:postgresql://postgres.zmon:5432/local_zmon_db
    "REDIS_HOST": redis.zmon
    "REDIS_PORT": 6379
    "ZMON_EVENTLOG_URL": http://eventlog-service.zmon:8081/
    "ZMON_KAIROSDB_URL": http://kairosdb.zmon:8083/
    "ZMON_METRICCACHE_URL": http://metric-cache.zmon:8086/
    "ZMON_SCHEDULER_URL": http://scheduler.zmon:8085/
    "SPRING_PROFILES_ACTIVE": github
    "ZMON_OAUTH2_SSO_CLIENT_ID": 09e23127316d4764f324
    "ZMON_OAUTH2_SSO_CLIENT_SECRET": d7b55e00f9ab7a1fc99f902df53c4baa4a013e25
    "ZMON_AUTHORITIES_SIMPLE_ADMINS": "*"
    "ZMON_TEAMS_SIMPLE_DEFAULT_TEAM": "ZMON"
    # "ZMON_SIGNUP_GITHUB_ALLOWED_USERS": "*"
    # "ZMON_SIGNUP_GITHUB_ALLOWED_ORGAS": "*"

zmon-worker:
  image_version: "cd215"
  env_vars:
    "WORKER_REDIS_SERVERS": redis:6379
    "WORKER_KAIROSDB_HOST": kairosdb.zmon
    "WORKER_METRICCACHE_URL": http://metric-cache.zmon:8086/api/v1/rest-api-metrics/
    "WORKER_METRICCACHE_CHECK_ID": 9
    "WORKER_EVENTLOG_HOST": eventlog-service.zmon
    "WORKER_EVENTLOG_PORT": 8081
    "WORKER_PLUGIN_SQL_USER": "zmon"

zmon-scheduler:
  image_version: "cd110"
  env_vars:
    "MEM_JAVA_PERCENT": 20
    "SCHEDULER_REDIS_HOST": redis.zmon
    "SCHEDULER_URLS_WITHOUT_REST": true
    "SCHEDULER_ENTITY_SERVICE_URL": http://controller.zmon:8080/
    "SCHEDULER_OAUTH2_STATIC_TOKEN": "$SCHEDULER_TOKEN"
    "SCHEDULER_CONTROLLER_URL": http://controller.zmon:8080/

zmon-eventlog-service:
  image_version: "cd16"
  env_vars:
    "SERVER_PORT": 8081
    "MEM_JAVA_PERCENT": 10
    "POSTGRESQL_HOST": postgres.zmon
    "POSTGRESQL_DATABASE": local_zmon_db
    "POSTGRESQL_USER": postgres

postgresql:
  image_version: "9.5.3-1"
