apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
  namespace: zmon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:9.5.3
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data
        ports:
        - containerPort: 5432
