apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: zmon
  labels:
    app: redis
spec:
  type: NodePort
  ports:
  - port: 6379
    targetPort: 6379
    nodePort: 31086
  selector:
    app: redis
