apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: zmon
spec:
  type: ClusterIP
  selector:
    app: zmon-controller
  ports:
    - port: 443
      targetPort: 443
      nodePort: 31443
      protocol: TCP
