apiVersion: v1
kind: Service
metadata:
  name: eventlog-service
  namespace: zmon
spec:
  selector:
    app: zmon-eventlog-service
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
