apiVersion: v1
kind: Service
metadata:
  name: scheduler
  namespace: zmon
spec:
  type: ClusterIP
  selector:
    app: zmon-scheduler
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
