apiVersion: v1
kind: Service
metadata:
  name: controller
  namespace: zmon
spec:
  type: LoadBalancer
  selector:
    app: zmon-controller
  ports:
    - port: 443
      targetPort: 443
      protocol: TCP
