apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: scheduler-deployment
  namespace: zmon
spec:  # specification of the pod's contents
  replicas: 1
  template:
    metadata:
      labels:
        app: zmon-scheduler
        version: {{image_version}}
    spec:
      containers:
        - name: zmon-scheduler
          image: "registry.opensource.zalan.do/stups/zmon-scheduler:{{image_version}}"
          env: {% for k,v in env_vars.items() %}
          - name: "{{ k }}"
            value: |-
              {{ v }}{% endfor %}
          ports:
          - containerPort: 8080
