apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: cassandra
  namespace: zmon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cassandra
    spec:
      containers:
      - name: cassandra
        image: cassandra:3.9
        ports:
        - containerPort: 9042
          name: cql
