
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: zmon
  labels:
    app: cassandra
spec:
  type: LoadBalancer
  ports:
  - port: 9160
    targetPort: 9160
  selector:
    app: cassandra
